/****** Carga de datos en tablas maestras  ******/

  /*---------- Carga de tipos de documento--------------*/
  INSERT INTO AMPAEXT.dbo.TIPO_DOCUMENTO
  (NOMBRE,DESCRIPCION)
  VALUES
  ('NIF', 'Número de Identificación Fiscal')

  INSERT INTO AMPAEXT.dbo.TIPO_DOCUMENTO
  (NOMBRE,DESCRIPCION)
  VALUES
  ('NIE', 'Número de Identidad de Extranjero')
  
  INSERT INTO AMPAEXT.dbo.TIPO_DOCUMENTO
  (NOMBRE,DESCRIPCION)
  VALUES
  ('OTRO', 'Otro tipo de documentación')
  /*---------- Fin --------------*/
  
  /*---------- Carga de decuentos--------------*/
  INSERT INTO AMPAEXT.dbo.DESCUENTO
  (NOMBRE)
  VALUES
  ('Inscrito más de un hijo')

  INSERT INTO AMPAEXT.dbo.DESCUENTO
  (NOMBRE)
  VALUES
  ('Familia numerosa')
  
  INSERT INTO AMPAEXT.dbo.DESCUENTO
  (NOMBRE)
  VALUES
  ('Desempleo')

  INSERT INTO AMPAEXT.dbo.DESCUENTO
  (NOMBRE)
  VALUES
  ('Renta mínima')
  
  /*---------- Fin --------------*/
  
  /*---------- Carga de cursos--------------*/
  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('Primero infantil')
  
  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('Segundo infantil')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('Tercero infantil')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('1º primaria')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('2º primaria')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('3º primaria')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('4º primaria')

  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('5º primaria')
  
  INSERT INTO AMPAEXT.dbo.CURSO
  (NOMBRE)
  VALUES
  ('6º primaria')
  /*---------- Fin --------------*/
  
  /*---------- Carga de clases--------------*/
  INSERT INTO AMPAEXT.dbo.CLASE
  (NOMBRE)
  VALUES
  ('A')
  
  INSERT INTO AMPAEXT.dbo.CLASE
  (NOMBRE)
  VALUES
  ('B')
  
  INSERT INTO AMPAEXT.dbo.CLASE
  (NOMBRE)
  VALUES
  ('C')
  
  INSERT INTO AMPAEXT.dbo.CLASE
  (NOMBRE)
  VALUES
  ('D')
  /*---------- Fin --------------*/
    
/********* Alta de una nueva AMPA  *********/
  /*---------- Carga de AMPA como entidad--------------*/
  INSERT INTO AMPAEXT.dbo.AMPA
  (NOMBRE, NIF, FECHA)
  VALUES
  ('AMPA Unir', '00000000T', GETDATE())	

   
  /*---------- Carga del usuario administrador del sistema --------------*/
  INSERT INTO AMPAEXT.dbo.USUARIO_AMPA
  (ID_AMPA, ID_TIPO_DOCUMENTO,NUMERO_DOCUMENTO,NOMBRE,APELLIDO1,APELLIDO2,EMAIL,TELEFONO,LOGIN,PASSWORD,OBSERVACIONES,FECHA,FECHA_MOD,USUARIO)
  SELECT ID_AMPA, (SELECT ID_TIPO_DOCUMENTO FROM AMPAEXT.dbo.TIPO_DOCUMENTO WHERE NOMBRE = 'NIF'), '12345678Z', 'usuario', 'apellido1', 'apellido2', 'correo@correo.net', '612345678', '12345678Z', '2558a34d4d20964ca1d272ab26ccce9511d880579593cd4c9e01ab91ed00f325', NULL, GETDATE(), NULL, 'SYS_ADMINISTRADOR'
  FROM AMPA
  WHERE NIF = '00000000T'
  
  /*---------- Fin --------------*/
  
  /*---------- Carga de cursos para la AMPA--------------*/
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(1,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(1,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(1,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(1,4,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(2,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(2,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(2,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(3,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(3,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(3,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(4,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(4,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(4,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(5,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(5,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(6,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(6,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(6,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(7,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(7,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(7,3,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(7,4,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(8,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(8,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(9,1,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(9,2,1)
INSERT INTO AMPAEXT.dbo.CURSO_CLASE(ID_CURSO,ID_CLASE,ID_AMPA)VALUES(9,3,1)
  
    /*---------- Fin --------------*/
  


