//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD_HORARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDAD_HORARIO()
        {
            this.ALUMNO_ACTIVIDAD = new HashSet<ALUMNO_ACTIVIDAD>();
        }
    
        public int ID_ACT_HORARIO { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public Nullable<int> ID_MONITOR { get; set; }
        public string DIAS { get; set; }
        public string HORA_INI { get; set; }
        public string HORA_FIN { get; set; }
        public decimal CUOTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
        public string USUARIO { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual MONITOR MONITOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALUMNO_ACTIVIDAD> ALUMNO_ACTIVIDAD { get; set; }
    }
}
