//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD_DESCUENTO
    {
        public int ID_ACT_DESCUENTO { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public int ID_DESCUENTO { get; set; }
        public int VALOR { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
        public string USUARIO { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual DESCUENTO DESCUENTO { get; set; }
    }
}
