//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO_ACTIVIDAD
    {
        public int ID_ALUM_ACT { get; set; }
        public int ID_ALUMNO { get; set; }
        public int ID_ACT_HORARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
        public string USUARIO { get; set; }
    
        public virtual ACTIVIDAD_HORARIO ACTIVIDAD_HORARIO { get; set; }
        public virtual ALUMNO ALUMNO { get; set; }
    }
}
