//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPA.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AMPAEXTBD : DbContext
    {
        public AMPAEXTBD()
            : base("name=AMPAEXTBD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIVIDAD> ACTIVIDAD { get; set; }
        public virtual DbSet<ACTIVIDAD_DESCUENTO> ACTIVIDAD_DESCUENTO { get; set; }
        public virtual DbSet<ACTIVIDAD_HORARIO> ACTIVIDAD_HORARIO { get; set; }
        public virtual DbSet<ALUMNO> ALUMNO { get; set; }
        public virtual DbSet<ALUMNO_ACTIVIDAD> ALUMNO_ACTIVIDAD { get; set; }
        public virtual DbSet<AMPA> AMPA { get; set; }
        public virtual DbSet<CLASE> CLASE { get; set; }
        public virtual DbSet<CURSO> CURSO { get; set; }
        public virtual DbSet<CURSO_CLASE> CURSO_CLASE { get; set; }
        public virtual DbSet<DESCUENTO> DESCUENTO { get; set; }
        public virtual DbSet<EMPRESA> EMPRESA { get; set; }
        public virtual DbSet<EMPRESA_AMPA> EMPRESA_AMPA { get; set; }
        public virtual DbSet<MONITOR> MONITOR { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TUTOR> TUTOR { get; set; }
        public virtual DbSet<USUARIO_AMPA> USUARIO_AMPA { get; set; }
        public virtual DbSet<USUARIO_EMPRESA> USUARIO_EMPRESA { get; set; }
    }
}
