//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMPA.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA_AMPA
    {
        public int ID_AMPA { get; set; }
        public int ID_EMPRESA { get; set; }
        public string ACTIVO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.DateTime> FECHA_MOD { get; set; }
        public string MOTIVO_BAJA { get; set; }
        public string USUARIO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual AMPA AMPA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
